-- CREATE USER api_user WITH PASSWORD 'Database1#CRU';

-- GRANT CONNECT ON DATABASE oncodb TO api_user;
-- GRANT USAGE ON SCHEMA public TO api_user;

-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO api_user;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA public
-- GRANT SELECT, INSERT, UPDATE ON TABLES TO api_user;